[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  command = "npm run build"

[context.admin]
  command = "npm run build"
  environment = { VITE_ADMIN_MODE = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"