// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdnbihrqujhmmgnshhhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbmJpaHJxdWpobW1nbnNoaGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MDc1MDksImV4cCI6MjA0OTM4MzUwOX0.8_j4MMocXgT3CRS9PPdwEeeKj9_ShGkZArWSltfc_m0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);